### ISSUE TITLE
Revisa si este programa funciona correctamente 

### ISSUE THREAD

**Issue by DaiM24** [DaiM24/Weather#1]
Advertencia! llevará mucho tiempo asi que les recomiendo que cancelen todas sus citas.. :c

**Comment by AlvaroFLD** [comment]
Perdón por ser tan directo. Pero el código no tiene fin alguno. No hace nada.

**Comment by DaiM24** [comment]
Estas despedido xD

**Comment by AlvaroFLD** [comment]
Cierro el issue y borro el codigo.

**Comment by DaiM24** [comment]
HOLA
